- name: Deploy web app running on nginx, php
  hosts: medium
  gather_facts: yes
  become: false
    - name: Installing nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Installing php
      apt:
        name:
          - php-fpm
          - php-cli
          - php-mysql
        state: present
      become: true